name: Update Changelog

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - name : "Install dependencies"
        run: npm i
      - name: Update Changelog
        run: |
          git config --global user.name 'CI'
          git config --global user.email 'ci@github.com'
          git fetch --all
          git branch
          git checkout develop
          npm run changelog
          git add CHANGELOG.md 
          git commit -m "[CI] Update changelog"
          git push
  deploy-docs:
    runs-on: ubuntu-latest
    needs: [publish-release, release]
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name : Install mkdocs ğŸ
        run: pip install mkdocs
      - name: Build the docs with mkdocs ğŸ“ƒ
        run: mkdocs build --clean --site-dir static/docs && rm static/docs/img/favicon.ico && cp static/favicon.ico static/docs/img/
      - name: Deploy documentation ğŸ“ƒ
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: static/docs